[build]
    base = "/"
    publish = "dist/"

[[redirects]]
    from = "/"
    to = "/index.html"
    status = 200

[[headers]]
    for = "/*"
    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
    for = "/index.html"
    [headers.values]
        Cache-Control = "no-cache, max-age=0, must-revalidate"
